export const mockCalls = [
  {
    id: '1',
    patientId: '1',
    patientName: 'John Doe',
    patientAvatar: 'https://i.pravatar.cc/150?img=1',
    scheduledTime: '09:00 AM',
    priority: 'routine',
    status: 'pending',
    medicationCount: 2,
    callTime: '2024-01-15T09:00:00',
    caretakerId: '1',
    caretakerName: 'Sarah Johnson',
    notes: '',
    outcome: '',
  },
  {
    id: '2',
    patientId: '2',
    patientName: 'Mary Smith',
    patientAvatar: 'https://i.pravatar.cc/150?img=2',
    scheduledTime: '09:30 AM',
    priority: 'routine',
    status: 'completed',
    medicationCount: 2,
    callTime: '2024-01-15T09:30:00',
    caretakerId: '2',
    caretakerName: 'Michael Chen',
    notes: 'Patient confirmed all medications taken',
    outcome: 'Answered & Completed',
    duration: '5:23',
  },
  {
    id: '3',
    patientId: '3',
    patientName: 'Robert Johnson',
    patientAvatar: 'https://i.pravatar.cc/150?img=3',
    scheduledTime: '10:00 AM',
    priority: 'urgent',
    status: 'overdue',
    medicationCount: 2,
    callTime: '2024-01-15T10:00:00',
    caretakerId: '3',
    caretakerName: 'Emily Davis',
    notes: '',
    outcome: '',
  },
  {
    id: '4',
    patientId: '4',
    patientName: 'Patricia Williams',
    patientAvatar: 'https://i.pravatar.cc/150?img=4',
    scheduledTime: '10:30 AM',
    priority: 'routine',
    status: 'pending',
    medicationCount: 3,
    callTime: '2024-01-15T10:30:00',
    caretakerId: '1',
    caretakerName: 'Sarah Johnson',
    notes: '',
    outcome: '',
  },
  {
    id: '5',
    patientId: '5',
    patientName: 'James Brown',
    patientAvatar: 'https://i.pravatar.cc/150?img=5',
    scheduledTime: '11:00 AM',
    priority: 'routine',
    status: 'completed',
    medicationCount: 2,
    callTime: '2024-01-15T11:00:00',
    caretakerId: '2',
    caretakerName: 'Michael Chen',
    notes: 'Insulin dose confirmed, blood sugar stable',
    outcome: 'Answered & Completed',
    duration: '7:45',
  },
  {
    id: '6',
    patientId: '6',
    patientName: 'Barbara Davis',
    patientAvatar: 'https://i.pravatar.cc/150?img=6',
    scheduledTime: '11:30 AM',
    priority: 'routine',
    status: 'pending',
    medicationCount: 2,
    callTime: '2024-01-15T11:30:00',
    caretakerId: '3',
    caretakerName: 'Emily Davis',
    notes: '',
    outcome: '',
  },
  {
    id: '7',
    patientId: '7',
    patientName: 'William Miller',
    patientAvatar: 'https://i.pravatar.cc/150?img=7',
    scheduledTime: '12:00 PM',
    priority: 'urgent',
    status: 'pending',
    medicationCount: 2,
    callTime: '2024-01-15T12:00:00',
    caretakerId: '1',
    caretakerName: 'Sarah Johnson',
    notes: 'Patient on warfarin - critical medication',
    outcome: '',
  },
  {
    id: '8',
    patientId: '8',
    patientName: 'Elizabeth Wilson',
    patientAvatar: 'https://i.pravatar.cc/150?img=8',
    scheduledTime: '02:00 PM',
    priority: 'routine',
    status: 'pending',
    medicationCount: 2,
    callTime: '2024-01-15T14:00:00',
    caretakerId: '2',
    caretakerName: 'Michael Chen',
    notes: '',
    outcome: '',
  },
  {
    id: '9',
    patientId: '1',
    patientName: 'John Doe',
    patientAvatar: 'https://i.pravatar.cc/150?img=1',
    scheduledTime: '02:30 PM',
    priority: 'routine',
    status: 'pending',
    medicationCount: 1,
    callTime: '2024-01-15T14:30:00',
    caretakerId: '1',
    caretakerName: 'Sarah Johnson',
    notes: '',
    outcome: '',
  },
  {
    id: '10',
    patientId: '3',
    patientName: 'Robert Johnson',
    patientAvatar: 'https://i.pravatar.cc/150?img=3',
    scheduledTime: '03:00 PM',
    priority: 'routine',
    status: 'pending',
    medicationCount: 1,
    callTime: '2024-01-15T15:00:00',
    caretakerId: '3',
    caretakerName: 'Emily Davis',
    notes: '',
    outcome: '',
  },
];
