export const mockCaretakers = [
  {
    id: '1',
    name: 'Sarah Johnson',
    avatar: 'https://i.pravatar.cc/150?img=25',
    status: 'available',
    assignedPatients: 12,
    performanceScore: 94,
    callsCompletedToday: 8,
    callsScheduledToday: 10,
    email: 'sarah.johnson@careconnect.com',
    phone: '555-1001',
    languages: ['English', 'Spanish'],
    hireDate: '2023-01-15',
  },
  {
    id: '2',
    name: 'Michael Chen',
    avatar: 'https://i.pravatar.cc/150?img=26',
    status: 'on_call',
    assignedPatients: 10,
    performanceScore: 89,
    callsCompletedToday: 6,
    callsScheduledToday: 8,
    email: 'michael.chen@careconnect.com',
    phone: '555-1002',
    languages: ['English', 'Mandarin'],
    hireDate: '2023-03-20',
  },
  {
    id: '3',
    name: 'Emily Davis',
    avatar: 'https://i.pravatar.cc/150?img=27',
    status: 'available',
    assignedPatients: 8,
    performanceScore: 92,
    callsCompletedToday: 7,
    callsScheduledToday: 9,
    email: 'emily.davis@careconnect.com',
    phone: '555-1003',
    languages: ['English'],
    hireDate: '2023-02-10',
  },
  {
    id: '4',
    name: 'James Wilson',
    avatar: 'https://i.pravatar.cc/150?img=28',
    status: 'off_duty',
    assignedPatients: 11,
    performanceScore: 87,
    callsCompletedToday: 0,
    callsScheduledToday: 0,
    email: 'james.wilson@careconnect.com',
    phone: '555-1004',
    languages: ['English', 'French'],
    hireDate: '2022-11-05',
  },
  {
    id: '5',
    name: 'Maria Garcia',
    avatar: 'https://i.pravatar.cc/150?img=29',
    status: 'available',
    assignedPatients: 9,
    performanceScore: 95,
    callsCompletedToday: 9,
    callsScheduledToday: 10,
    email: 'maria.garcia@careconnect.com',
    phone: '555-1005',
    languages: ['English', 'Spanish'],
    hireDate: '2023-04-12',
  },
  {
    id: '6',
    name: 'Robert Taylor',
    avatar: 'https://i.pravatar.cc/150?img=30',
    status: 'on_call',
    assignedPatients: 7,
    performanceScore: 85,
    callsCompletedToday: 5,
    callsScheduledToday: 7,
    email: 'robert.taylor@careconnect.com',
    phone: '555-1006',
    languages: ['English'],
    hireDate: '2023-05-18',
  },
  {
    id: '7',
    name: 'Lisa Anderson',
    avatar: 'https://i.pravatar.cc/150?img=31',
    status: 'available',
    assignedPatients: 13,
    performanceScore: 91,
    callsCompletedToday: 8,
    callsScheduledToday: 11,
    email: 'lisa.anderson@careconnect.com',
    phone: '555-1007',
    languages: ['English', 'German'],
    hireDate: '2022-09-22',
  },
  {
    id: '8',
    name: 'David Martinez',
    avatar: 'https://i.pravatar.cc/150?img=32',
    status: 'off_duty',
    assignedPatients: 6,
    performanceScore: 88,
    callsCompletedToday: 0,
    callsScheduledToday: 0,
    email: 'david.martinez@careconnect.com',
    phone: '555-1008',
    languages: ['English', 'Spanish'],
    hireDate: '2023-06-30',
  },
];
