export const mockMedications = [
  {
    id: '1',
    patientId: '1',
    name: 'Metformin',
    dosage: '500mg',
    time: '08:00 AM',
    frequency: 'Daily',
    withFood: true,
    instructions: 'Take with breakfast',
    taken: false,
    prescribedBy: 'Dr. Smith',
    startDate: '2023-01-15',
  },
  {
    id: '2',
    patientId: '1',
    name: 'Lisinopril',
    dosage: '10mg',
    time: '08:00 AM',
    frequency: 'Daily',
    withFood: false,
    instructions: 'Take on empty stomach',
    taken: false,
    prescribedBy: 'Dr. Johnson',
    startDate: '2023-02-20',
  },
  {
    id: '3',
    patientId: '2',
    name: 'Aspirin',
    dosage: '81mg',
    time: '09:00 AM',
    frequency: 'Daily',
    withFood: true,
    instructions: 'Low dose aspirin for heart health',
    taken: true,
    prescribedBy: 'Dr. Williams',
    startDate: '2023-03-10',
  },
  {
    id: '4',
    patientId: '2',
    name: 'Atorvastatin',
    dosage: '20mg',
    time: '08:00 PM',
    frequency: 'Daily',
    withFood: true,
    instructions: 'Take with evening meal',
    taken: false,
    prescribedBy: 'Dr. Brown',
    startDate: '2023-01-05',
  },
  {
    id: '5',
    patientId: '3',
    name: 'Metoprolol',
    dosage: '25mg',
    time: '08:00 AM',
    frequency: 'Twice daily',
    withFood: false,
    instructions: 'Take morning and evening',
    taken: true,
    prescribedBy: 'Dr. Davis',
    startDate: '2023-04-15',
  },
  {
    id: '6',
    patientId: '3',
    name: 'Furosemide',
    dosage: '40mg',
    time: '08:00 AM',
    frequency: 'Daily',
    withFood: true,
    instructions: 'Take with food, avoid evening doses',
    taken: false,
    prescribedBy: 'Dr. Miller',
    startDate: '2023-02-28',
  },
  {
    id: '7',
    patientId: '4',
    name: 'Levothyroxine',
    dosage: '50mcg',
    time: '07:00 AM',
    frequency: 'Daily',
    withFood: false,
    instructions: 'Take 30 minutes before breakfast',
    taken: true,
    prescribedBy: 'Dr. Wilson',
    startDate: '2023-01-10',
  },
  {
    id: '8',
    patientId: '4',
    name: 'Calcium',
    dosage: '600mg',
    time: '12:00 PM',
    frequency: 'Twice daily',
    withFood: true,
    instructions: 'Take with meals',
    taken: false,
    prescribedBy: 'Dr. Moore',
    startDate: '2023-03-20',
  },
  {
    id: '9',
    patientId: '5',
    name: 'Insulin',
    dosage: '10 units',
    time: '08:00 AM',
    frequency: 'Twice daily',
    withFood: false,
    instructions: 'Take before meals',
    taken: false,
    prescribedBy: 'Dr. Taylor',
    startDate: '2023-05-01',
  },
  {
    id: '10',
    patientId: '5',
    name: 'Metformin',
    dosage: '1000mg',
    time: '08:00 AM',
    frequency: 'Twice daily',
    withFood: true,
    instructions: 'Take with meals',
    taken: false,
    prescribedBy: 'Dr. Anderson',
    startDate: '2023-04-10',
  },
];
