export const mockAlerts = [
  {
    id: '1',
    patientName: 'John Doe',
    patientId: '1',
    type: 'missed_medication',
    priority: 'high',
    caretaker: 'Sarah Johnson',
    caretakerId: '1',
    timestamp: '2024-01-15T14:30:00',
    status: 'unresolved',
    message: 'Patient did not answer call for afternoon medication',
    assignedTo: '',
  },
  {
    id: '2',
    patientName: 'Robert Johnson',
    patientId: '3',
    type: 'no_answer',
    priority: 'medium',
    caretaker: 'Emily Davis',
    caretakerId: '3',
    timestamp: '2024-01-15T10:15:00',
    status: 'unresolved',
    message: 'Multiple call attempts, no response from patient',
    assignedTo: '',
  },
  {
    id: '3',
    patientName: 'William Miller',
    patientId: '7',
    type: 'critical_medication',
    priority: 'high',
    caretaker: 'Sarah Johnson',
    caretakerId: '1',
    timestamp: '2024-01-15T12:05:00',
    status: 'resolved',
    message: 'Warfarin dose confirmation required - patient contacted successfully',
    assignedTo: 'Sarah Johnson',
    resolvedAt: '2024-01-15T12:45:00',
  },
  {
    id: '4',
    patientName: 'Mary Smith',
    patientId: '2',
    type: 'adverse_reaction',
    priority: 'high',
    caretaker: 'Michael Chen',
    caretakerId: '2',
    timestamp: '2024-01-15T09:45:00',
    status: 'resolved',
    message: 'Patient reported dizziness after medication - advised to contact doctor',
    assignedTo: 'Michael Chen',
    resolvedAt: '2024-01-15T10:30:00',
  },
  {
    id: '5',
    patientName: 'James Brown',
    patientId: '5',
    type: 'low_adherence',
    priority: 'medium',
    caretaker: 'Michael Chen',
    caretakerId: '2',
    timestamp: '2024-01-15T11:20:00',
    status: 'unresolved',
    message: 'Patient adherence rate below 80% for past week',
    assignedTo: '',
  },
  {
    id: '6',
    patientName: 'Elizabeth Wilson',
    patientId: '8',
    type: 'medication_refill',
    priority: 'low',
    caretaker: 'Michael Chen',
    caretakerId: '2',
    timestamp: '2024-01-15T13:00:00',
    status: 'unresolved',
    message: 'Gabapentin prescription needs refill in 5 days',
    assignedTo: '',
  },
  {
    id: '7',
    patientName: 'Barbara Davis',
    patientId: '6',
    type: 'appointment_reminder',
    priority: 'low',
    caretaker: 'Emily Davis',
    caretakerId: '3',
    timestamp: '2024-01-15T08:00:00',
    status: 'resolved',
    message: 'Bone density scan appointment tomorrow at 2 PM',
    assignedTo: 'Emily Davis',
    resolvedAt: '2024-01-15T08:15:00',
  },
  {
    id: '8',
    patientName: 'Patricia Williams',
    patientId: '4',
    type: 'emergency_contact',
    priority: 'high',
    caretaker: 'Sarah Johnson',
    caretakerId: '1',
    timestamp: '2024-01-15T10:30:00',
    status: 'unresolved',
    message: 'Emergency contact requested medication schedule update',
    assignedTo: '',
  },
];
