export const mockPatients = [
  {
    id: '1',
    name: 'John Doe',
    age: 68,
    avatar: 'https://i.pravatar.cc/150?img=1',
    assignedCaretaker: 'Sarah Johnson',
    adherenceRate: 87,
    status: 'active',
    lastCallDate: '2024-01-15',
    medications: [
      { name: 'Metformin', dosage: '500mg', time: '08:00 AM', frequency: 'Daily' },
      { name: 'Lisinopril', dosage: '10mg', time: '08:00 AM', frequency: 'Daily' },
    ],
    allergies: ['Penicillin'],
    emergencyContact: { name: 'Jane Doe', phone: '555-0123', relation: 'Daughter' },
  },
  {
    id: '2',
    name: 'Mary Smith',
    age: 72,
    avatar: 'https://i.pravatar.cc/150?img=2',
    assignedCaretaker: 'Michael Chen',
    adherenceRate: 92,
    status: 'active',
    lastCallDate: '2024-01-15',
    medications: [
      { name: 'Aspirin', dosage: '81mg', time: '09:00 AM', frequency: 'Daily' },
      { name: 'Atorvastatin', dosage: '20mg', time: '08:00 PM', frequency: 'Daily' },
    ],
    allergies: ['None'],
    emergencyContact: { name: 'Robert Smith', phone: '555-0124', relation: 'Son' },
  },
  {
    id: '3',
    name: 'Robert Johnson',
    age: 65,
    avatar: 'https://i.pravatar.cc/150?img=3',
    assignedCaretaker: 'Emily Davis',
    adherenceRate: 78,
    status: 'active',
    lastCallDate: '2024-01-14',
    medications: [
      { name: 'Metoprolol', dosage: '25mg', time: '08:00 AM', frequency: 'Twice daily' },
      { name: 'Furosemide', dosage: '40mg', time: '08:00 AM', frequency: 'Daily' },
    ],
    allergies: ['Sulfa drugs'],
    emergencyContact: { name: 'Linda Johnson', phone: '555-0125', relation: 'Wife' },
  },
  {
    id: '4',
    name: 'Patricia Williams',
    age: 80,
    avatar: 'https://i.pravatar.cc/150?img=4',
    assignedCaretaker: 'Sarah Johnson',
    adherenceRate: 95,
    status: 'active',
    lastCallDate: '2024-01-15',
    medications: [
      { name: 'Levothyroxine', dosage: '50mcg', time: '07:00 AM', frequency: 'Daily' },
      { name: 'Calcium', dosage: '600mg', time: '12:00 PM', frequency: 'Twice daily' },
      { name: 'Vitamin D', dosage: '1000IU', time: '08:00 AM', frequency: 'Daily' },
    ],
    allergies: ['None'],
    emergencyContact: { name: 'James Williams', phone: '555-0126', relation: 'Son' },
  },
  {
    id: '5',
    name: 'James Brown',
    age: 75,
    avatar: 'https://i.pravatar.cc/150?img=5',
    assignedCaretaker: 'Michael Chen',
    adherenceRate: 82,
    status: 'active',
    lastCallDate: '2024-01-14',
    medications: [
      { name: 'Insulin', dosage: '10 units', time: '08:00 AM', frequency: 'Twice daily' },
      { name: 'Metformin', dosage: '1000mg', time: '08:00 AM', frequency: 'Twice daily' },
    ],
    allergies: ['None'],
    emergencyContact: { name: 'Susan Brown', phone: '555-0127', relation: 'Daughter' },
  },
  {
    id: '6',
    name: 'Barbara Davis',
    age: 69,
    avatar: 'https://i.pravatar.cc/150?img=6',
    assignedCaretaker: 'Emily Davis',
    adherenceRate: 88,
    status: 'active',
    lastCallDate: '2024-01-15',
    medications: [
      { name: 'Alendronate', dosage: '70mg', time: '08:00 AM', frequency: 'Weekly' },
      { name: 'Calcium', dosage: '600mg', time: '12:00 PM', frequency: 'Twice daily' },
    ],
    allergies: ['NSAIDs'],
    emergencyContact: { name: 'Thomas Davis', phone: '555-0128', relation: 'Husband' },
  },
  {
    id: '7',
    name: 'William Miller',
    age: 71,
    avatar: 'https://i.pravatar.cc/150?img=7',
    assignedCaretaker: 'Sarah Johnson',
    adherenceRate: 73,
    status: 'paused',
    lastCallDate: '2024-01-10',
    medications: [
      { name: 'Warfarin', dosage: '5mg', time: '06:00 PM', frequency: 'Daily' },
      { name: 'Digoxin', dosage: '0.125mg', time: '08:00 AM', frequency: 'Daily' },
    ],
    allergies: ['Penicillin'],
    emergencyContact: { name: 'Margaret Miller', phone: '555-0129', relation: 'Wife' },
  },
  {
    id: '8',
    name: 'Elizabeth Wilson',
    age: 77,
    avatar: 'https://i.pravatar.cc/150?img=8',
    assignedCaretaker: 'Michael Chen',
    adherenceRate: 91,
    status: 'active',
    lastCallDate: '2024-01-15',
    medications: [
      { name: 'Gabapentin', dosage: '300mg', time: '08:00 AM', frequency: 'Three times daily' },
      { name: 'Sertraline', dosage: '50mg', time: '09:00 AM', frequency: 'Daily' },
    ],
    allergies: ['None'],
    emergencyContact: { name: 'David Wilson', phone: '555-0130', relation: 'Son' },
  },
];
